// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    return $.fn.extend({
      creatsnow: function(n, SP, symbol) {
        var h, h1, i, sn, snow, snowbody1, snowbox, sph, w, w1, _i;
        w = ($(this)).width();
        h = ($(this)).height();
        sph = 2 * h;
        sn = 100;
        snowbox = $("<div></div>");
        snowbody1 = $("<div></div").css({
          "width": w,
          "height": h,
          "position": "relative",
          "margin": 0
        });
        if (n) {
          sn = n;
        }
        if (symbol === "snow" || symbol === void 0) {
          for (i = _i = 0; 0 <= sn ? _i <= sn : _i >= sn; i = 0 <= sn ? ++_i : --_i) {
            snow = $("<div></div>");
            snow.addClass("snow");
            h1 = Math.random() * h;
            w1 = Math.random() * w;
            snow.css({
              "position": "absolute",
              "top": h1,
              "left": w1
            });
            snowbody1.append(snow);
          }
          snowbox.append(snowbody1);
          if (SP) {
            sph = h;
          }
          snowbox.append(snowbody1.clone()).css({
            "top": "-" + sph + "px",
            "height": sph + "px",
            "position": "absolute"
          });
          return $(this).append(snowbox).css("overflow", "hidden");
        }
      },
      started: function(speed) {
        var h, i, obj;
        h = ($(this)).height();
        obj = ($(this)).children();
        i = parseInt(obj.css("top"));
        h = 0 - parseInt(h);
        return setInterval(function() {
          if (i < 0) {
            obj.css("top", i + "px");
            return i = i + speed;
          } else {
            return i = h;
          }
        }, 1);
      }
    });
  });

}).call(this);
